"""Fixed Created tables with relationships

Revision ID: 9720c60e21d7
Revises: 49059a86a9b4
Create Date: 2025-07-24 15:09:24.086599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9720c60e21d7'
down_revision = '49059a86a9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speakers',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_session_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('sessions_speakers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_speakers',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_sessions_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_sessions_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('session_speakers')
    # ### end Alembic commands ###
